version: "2.4"
services:
    web:
        build: . 
        image: pradeeprajr93/notes-api:v3
        ports:
        - "3000:3000"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
        - "27017:27017"