apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: pradeeprajr93/notes-api:v8
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: mongo-api-config
                key: mongo-db-endpoint
          - name: MONGO_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: notes-mongo-secret
                key: mongo-root-username
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notes-mongo-secret
                key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
spec:
  type: LoadBalancer
  selector:
    app: notes-api
  ports:
  - port: 3000
    targetPort: 3000

